apiVersion: apps/v1
kind: Deployment
metadata:
  name: asg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asg
  template:
    metadata:
      labels:
        app: asg
    spec:
      containers:
      - name: asgbug
        image: "sarojamarraj/asg:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: asg
    k8s-app: asg
  name: asg
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: asg
